name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:    #name of the image of the container
      image: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb # same as the docker image settings
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017 # same as the port of the docker image used for connecting
      MONGODB_USERNAME: root  # The username and password should be same as the docker image
      MONGODB_PASSWORD: example
      PORT: 8080
    # Adding a service to the Job  
    services:    # we can define one or more services in a single job
      mongodb:   # label - we are defining mongo db image for our job to run
        image: mongo
        ports:
          - 27017:27017
        env:                 # environment variables are mandate for this image
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
